// Auto-generated from Main Airports.json (merged with existing entries)
export const airportToCountry = {
  "ABQ": "United States",
  "ABV": "Nigeria",
  "ACC": "Ghana",
  "ACE": "Spain",
  "ADB": "Türkiye",
  "ADD": "Ethiopia",
  "ADL": "Australia",
  "ADW": "United States",
  "AEP": "Argentina",
  "AER": "Russia",
  "AGA": "Morocco",
  "AGP": "Spain",
  "AGT": "Paraguay",
  "AKL": "New Zealand",
  "ALA": "Kazakhstan",
  "ALC": "Spain",
  "ALG": "Algeria",
  "AMM": "Jordan",
  "AMS": "Netherlands",
  "ANC": "United States",
  "ARN": "Sweden",
  "ASB": "Turkmenistan",
  "ASU": "Paraguay",
  "ATH": "Greece",
  "ATL": "United States",
  "AUA": "Aruba",
  "AUH": "United Arab Emirates",
  "AUS": "United States",
  "AYT": "Türkiye",
  "BAH": "Bahrain",
  "BCN": "Spain",
  "BDL": "United States",
  "BDS": "Italy",
  "BEG": "Serbia",
  "BEL": "Brazil",
  "BER": "Germany",
  "BEY": "Lebanon",
  "BFS": "United Kingdom",
  "BGO": "Norway",
  "BGW": "Iraq",
  "BGY": "Italy",
  "BHX": "United Kingdom",
  "BJL": "Gambia",
  "BJV": "Türkiye",
  "BKK": "Thailand",
  "BKO": "Mali",
  "BLA": "Venezuela",
  "BLL": "Denmark",
  "BLQ": "Italy",
  "BLR": "India",
  "BNA": "United States",
  "BNE": "Australia",
  "BOD": "France",
  "BOG": "Colombia",
  "BOJ": "Bulgaria",
  "BOM": "India",
  "BON": "Caribbean Netherlands",
  "BOS": "United States",
  "BPN": "Indonesia",
  "BPS": "Brazil",
  "BRI": "Italy",
  "BRS": "United Kingdom",
  "BRU": "Belgium",
  "BSB": "Brazil",
  "BSL": "France",
  "BTS": "Slovakia",
  "BUD": "Hungary",
  "BUF": "United States",
  "BWI": "United States",
  "BWN": "Brunei",
  "BZE": "Belize",
  "CAG": "Italy",
  "CAI": "Egypt",
  "CAN": "China",
  "CAY": "French Guiana",
  "CCS": "Venezuela",
  "CCU": "India",
  "CDG": "France",
  "CEB": "Philippines",
  "CGK": "Indonesia",
  "CGN": "Germany",
  "CGO": "China",
  "CGQ": "China",
  "CHC": "New Zealand",
  "CJU": "South Korea",
  "CKG": "China",
  "CLE": "United States",
  "CLT": "United States",
  "CMB": "Sri Lanka",
  "CMH": "United States",
  "CMN": "Morocco",
  "CNF": "Brazil",
  "CNX": "Thailand",
  "COK": "India",
  "COV": "Türkiye",
  "CPH": "Denmark",
  "CPT": "South Africa",
  "CSX": "China",
  "CTA": "Italy",
  "CTS": "Japan",
  "CTU": "China",
  "CUN": "Mexico",
  "CUR": "Curaçao",
  "CUZ": "Peru",
  "CVG": "United States",
  "CZM": "Mexico",
  "DAC": "Bangladesh",
  "DAM": "Syria",
  "DAR": "Tanzania",
  "DCA": "United States",
  "DEL": "India",
  "DEN": "United States",
  "DFW": "United States",
  "DGO": "Mexico",
  "DHA": "Saudi Arabia",
  "DHX": "Indonesia",
  "DJJ": "Indonesia",
  "DLC": "China",
  "DLM": "Türkiye",
  "DME": "Russia",
  "DMK": "Thailand",
  "DMM": "Saudi Arabia",
  "DNA": "Japan",
  "DOH": "Qatar",
  "DPS": "Indonesia",
  "DQM": "Oman",
  "DRW": "Australia",
  "DSS": "Senegal",
  "DTW": "United States",
  "DUB": "Ireland",
  "DUR": "South Africa",
  "DUS": "Germany",
  "DVO": "Philippines",
  "DWC": "United Arab Emirates",
  "DXB": "United Arab Emirates",
  "EBB": "Uganda",
  "EDI": "United Kingdom",
  "EHU": "China",
  "EIN": "Netherlands",
  "ENO": "Paraguay",
  "ESB": "Türkiye",
  "ESG": "Paraguay",
  "ETM": "Israel",
  "EVN": "Armenia",
  "EWR": "United States",
  "EZE": "Argentina",
  "FAO": "Portugal",
  "FCO": "Italy",
  "FDF": "Martinique",
  "FEZ": "Morocco",
  "FIH": "Congo - Kinshasa",
  "FLL": "United States",
  "FLN": "Brazil",
  "FLR": "Italy",
  "FNA": "Sierra Leone",
  "FNC": "Portugal",
  "FNJ": "North Korea",
  "FOC": "China",
  "FOR": "Brazil",
  "FRA": "Germany",
  "FRU": "Kyrgyzstan",
  "FUE": "Spain",
  "FUK": "Japan",
  "GBE": "Botswana",
  "GCM": "Cayman Islands",
  "GDL": "Mexico",
  "GDN": "Poland",
  "GIB": "Gibraltar",
  "GIG": "Brazil",
  "GLA": "United Kingdom",
  "GMP": "South Korea",
  "GOA": "Italy",
  "GOI": "India",
  "GOT": "Sweden",
  "GOX": "India",
  "GRU": "Brazil",
  "GSV": "Russia",
  "GUA": "Guatemala",
  "GUM": "Guam",
  "GVA": "Switzerland",
  "GYD": "Azerbaijan",
  "GYE": "Ecuador",
  "HAJ": "Germany",
  "HAK": "China",
  "HAM": "Germany",
  "HAN": "Vietnam",
  "HAV": "Cuba",
  "HEL": "Finland",
  "HER": "Greece",
  "HET": "China",
  "HGH": "China",
  "HIR": "Solomon Islands",
  "HKG": "Hong Kong SAR China",
  "HKT": "Thailand",
  "HMB": "Egypt",
  "HND": "Japan",
  "HNL": "United States",
  "HRB": "China",
  "HRE": "Zimbabwe",
  "HRG": "Egypt",
  "HRI": "Sri Lanka",
  "HSR": "India",
  "HYD": "India",
  "IAD": "United States",
  "IAH": "United States",
  "IBZ": "Spain",
  "ICN": "South Korea",
  "IKA": "Iran",
  "IND": "United States",
  "ISB": "Pakistan",
  "IST": "Türkiye",
  "ITM": "Japan",
  "JAX": "United States",
  "JED": "Saudi Arabia",
  "JFK": "United States",
  "JIB": "Djibouti",
  "JNB": "South Africa",
  "JUB": "South Sudan",
  "KBP": "Ukraine",
  "KEF": "Iceland",
  "KGL": "Rwanda",
  "KHH": "Taiwan",
  "KHI": "Pakistan",
  "KHN": "China",
  "KIN": "Jamaica",
  "KIX": "Japan",
  "KJA": "Russia",
  "KMG": "China",
  "KNO": "Indonesia",
  "KOJ": "Japan",
  "KRK": "Poland",
  "KRT": "Sudan",
  "KTM": "Nepal",
  "KUF": "Russia",
  "KUL": "Malaysia",
  "KWE": "China",
  "KWI": "Kuwait",
  "KWL": "China",
  "KZN": "Russia",
  "LAD": "Angola",
  "LAS": "United States",
  "LAX": "United States",
  "LCA": "Cyprus",
  "LCJ": "United Kingdom",
  "LCY": "United Kingdom",
  "LED": "Russia",
  "LEJ": "Germany",
  "LGA": "United States",
  "LGW": "United Kingdom",
  "LHE": "Pakistan",
  "LHR": "United Kingdom",
  "LHW": "China",
  "LIM": "Peru",
  "LIR": "Costa Rica",
  "LIS": "Portugal",
  "LJU": "Slovenia",
  "LOS": "Nigeria",
  "LPA": "Spain",
  "LRM": "Dominican Republic",
  "LTN": "United Kingdom",
  "LUN": "Zambia",
  "LUX": "Luxembourg",
  "LWO": "Ukraine",
  "LYS": "France",
  "MAA": "India",
  "MAD": "Spain",
  "MAN": "United Kingdom",
  "MAO": "Brazil",
  "MBA": "Kenya",
  "MCI": "United States",
  "MCO": "United States",
  "MCT": "Oman",
  "MDL": "Myanmar (Burma)",
  "MDW": "United States",
  "MED": "Saudi Arabia",
  "MEL": "Australia",
  "MEM": "United States",
  "MEX": "Mexico",
  "MFM": "Macao SAR China",
  "MHD": "Iran",
  "MIA": "United States",
  "MID": "Mexico",
  "MJI": "Libya",
  "MKE": "United States",
  "MLA": "Malta",
  "MLE": "Maldives",
  "MNL": "Philippines",
  "MPM": "Mozambique",
  "MRS": "France",
  "MRU": "Mauritius",
  "MSP": "United States",
  "MSQ": "Belarus",
  "MSY": "United States",
  "MTY": "Mexico",
  "MUC": "Germany",
  "MVD": "Uruguay",
  "MWX": "South Korea",
  "MXP": "Italy",
  "MZT": "Mexico",
  "NAP": "Italy",
  "NAS": "Bahamas",
  "NBO": "Kenya",
  "NCE": "France",
  "NDJ": "Chad",
  "NGB": "China",
  "NGO": "Japan",
  "NIM": "Niger",
  "NKC": "Mauritania",
  "NKG": "China",
  "NLU": "Mexico",
  "NMI": "India",
  "NNG": "China",
  "NQZ": "Kazakhstan",
  "NRT": "Japan",
  "NUE": "Germany",
  "OAK": "United States",
  "OGG": "United States",
  "OKA": "Japan",
  "OKC": "United States",
  "OKO": "Japan",
  "OMA": "United States",
  "ONT": "United States",
  "OPO": "Portugal",
  "ORD": "United States",
  "ORF": "United States",
  "ORY": "France",
  "OSL": "Norway",
  "OTP": "Romania",
  "OVB": "Russia",
  "PAP": "Haiti",
  "PBI": "United States",
  "PBM": "Suriname",
  "PDL": "Portugal",
  "PDX": "United States",
  "PEK": "China",
  "PER": "Australia",
  "PFO": "Cyprus",
  "PHL": "United States",
  "PHX": "United States",
  "PIT": "United States",
  "PKX": "China",
  "PLS": "Turks & Caicos Islands",
  "PMI": "Spain",
  "PMO": "Italy",
  "PNH": "Cambodia",
  "POM": "Papua New Guinea",
  "PPT": "French Polynesia",
  "PRG": "Czechia",
  "PSA": "Italy",
  "PTP": "Guadeloupe",
  "PTY": "Panama",
  "PUJ": "Dominican Republic",
  "PUS": "South Korea",
  "PVD": "United States",
  "PVG": "China",
  "PVR": "Mexico",
  "PWM": "United States",
  "RAI": "Cape Verde",
  "RAK": "Morocco",
  "RBA": "Morocco",
  "RDU": "United States",
  "RGN": "Myanmar (Burma)",
  "RIC": "United States",
  "RIX": "Latvia",
  "RNO": "United States",
  "ROB": "Liberia",
  "ROV": "Russia",
  "RSW": "United States",
  "RUH": "Saudi Arabia",
  "RUN": "Réunion",
  "SAI": "Cambodia",
  "SAL": "El Salvador",
  "SAN": "United States",
  "SAT": "United States",
  "SAV": "United States",
  "SAW": "Türkiye",
  "SCL": "Chile",
  "SCQ": "Spain",
  "SDF": "United States",
  "SDJ": "Japan",
  "SDQ": "Dominican Republic",
  "SEA": "United States",
  "SEZ": "Seychelles",
  "SFB": "United States",
  "SFO": "United States",
  "SGN": "Vietnam",
  "SHA": "China",
  "SHE": "China",
  "SHJ": "United Arab Emirates",
  "SHO": "Eswatini",
  "SID": "Cape Verde",
  "SIN": "Singapore",
  "SJC": "United States",
  "SJD": "Mexico",
  "SJJ": "Bosnia & Herzegovina",
  "SJO": "Costa Rica",
  "SJU": "Puerto Rico",
  "SKG": "Greece",
  "SKP": "North Macedonia",
  "SLC": "United States",
  "SMF": "United States",
  "SNA": "United States",
  "SNN": "Ireland",
  "SOF": "Bulgaria",
  "SRQ": "United States",
  "SSA": "Brazil",
  "SSH": "Egypt",
  "STL": "United States",
  "STN": "United Kingdom",
  "STR": "Germany",
  "SUB": "Indonesia",
  "SVG": "Norway",
  "SVO": "Russia",
  "SVX": "Russia",
  "SXM": "Sint Maarten",
  "SYD": "Australia",
  "SYR": "United States",
  "SYX": "China",
  "SYZ": "Iran",
  "SZX": "China",
  "TAO": "China",
  "TAS": "Uzbekistan",
  "TBS": "Georgia",
  "TFS": "Spain",
  "TFU": "China",
  "TGD": "Montenegro",
  "THR": "Iran",
  "TIA": "Albania",
  "TIJ": "Mexico",
  "TLL": "Estonia",
  "TLS": "France",
  "TLV": "Israel",
  "TMS": "São Tomé & Príncipe",
  "TNA": "China",
  "TNG": "Morocco",
  "TNR": "Madagascar",
  "TOS": "Norway",
  "TPA": "United States",
  "TPE": "Taiwan",
  "TRD": "Norway",
  "TRN": "Italy",
  "TRV": "India",
  "TSN": "China",
  "TUL": "United States",
  "TUN": "Tunisia",
  "TYN": "China",
  "UBN": "Mongolia",
  "UFA": "Russia",
  "UIO": "Ecuador",
  "UPG": "Indonesia",
  "URC": "China",
  "UVF": "St. Lucia",
  "VAR": "Bulgaria",
  "VCE": "Italy",
  "VIE": "Austria",
  "VIX": "Brazil",
  "VKO": "Russia",
  "VLI": "Vanuatu",
  "VNO": "Lithuania",
  "VRA": "Cuba",
  "VRN": "Italy",
  "VVI": "Bolivia",
  "VVO": "Russia",
  "WAW": "Poland",
  "WDH": "Namibia",
  "WLG": "New Zealand",
  "WNZ": "China",
  "WUH": "China",
  "XIY": "China",
  "XMN": "China",
  "YEG": "Canada",
  "YHZ": "Canada",
  "YNT": "China",
  "YOW": "Canada",
  "YQB": "Canada",
  "YUL": "Canada",
  "YVR": "Canada",
  "YWG": "Canada",
  "YYC": "Canada",
  "YYT": "Canada",
  "YYZ": "Canada",
  "ZAG": "Croatia",
  "ZIA": "Russia",
  "ZNZ": "Tanzania",
  "ZRH": "Switzerland"
};
